### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Wutianhao-lab** [wwdguu/pyCFTrackers#14]
你好，我在pycharm上运行了您的代码，可是一直报错编译不成功。不知道是不是配置环境的问题。可以的话希望您可以出一个如何运行您文件的说明，这样会容易上手一些。非常感谢。

**Comment by fengyang95** [comment]
按照README里面的步骤就能运行成功哦，再试下呢

**Comment by momo-github-1984** [comment]
您好，我也遇到了类似的问题。我总是无法导入_gradient.cpp，这导致大多数追踪器如DSST、Staple、KCF等运行时会发生错误。我是在windows系统下，python3.6环境下运行的，也有MinGW和cs2015这些C++的编译环境，想请教您，为什么_gradient.cpp无法导入，我应该怎样解决？？
期待您的回复。

**Comment by fengyang95** [comment]
> 您好，我也遇到了类似的问题。我总是无法导入_gradient.cpp，这导致大多数追踪器如DSST、Staple、KCF等运行时会发生错误。我是在windows系统下，python3.6环境下运行的，也有MinGW和cs2015这些C++的编译环境，想请教您，为什么_gradient.cpp无法导入，我应该怎样解决？？
> 期待您的回复。

按照Readme里操作了吗？不好意思哦 我这边只在linux下测试过，不清楚windows下是否能运行

**Comment by momo-github-1984** [comment]
是按照Readme里操作的。只有调用_gradient.cpp的追踪器才会出错，其他的没有问题……您有好的办法可以帮我解决吗，比如我应该对_gradient.cpp进行一些修改？
我试图用cppimport去调用_gradient.cpp，还是会报错。

**Comment by fengyang95** [comment]
> 是按照Readme里操作的。只有调用_gradient.cpp的追踪器才会出错，其他的没有问题……您有好的办法可以帮我解决吗，比如我应该对_gradient.cpp进行一些修改？
> 我试图用cppimport去调用_gradient.cpp，还是会报错。

贴下具体报错信息？

**Comment by momo-github-1984** [comment]
C:\Users\18382\.conda\envs\tensorflow-m\python.exe "C:/Users/18382/Desktop/experiment/GitHub/pyCFTrackers-master (2)/pyCFTrackers-master/examples/cf_demo.py"
Traceback (most recent call last):
  File "C:/Users/18382/Desktop/experiment/GitHub/pyCFTrackers-master (2)/pyCFTrackers-master/examples/cf_demo.py", line 2, in <module>
    from examples.pytracker import PyTracker
  File "C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master (2)\pyCFTrackers-master\examples\pytracker.py", line 6, in <module>
    from cftracker.kcf import KCF
  File "C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master (2)\pyCFTrackers-master\cftracker\kcf.py", line 7, in <module>
    from .feature import extract_hog_feature,extract_cn_feature
  File "C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master (2)\pyCFTrackers-master\cftracker\feature.py", line 3, in <module>
    from lib.eco.features.features import fhog,TableFeature
  File "C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master (2)\pyCFTrackers-master\lib\eco\__init__.py", line 1, in <module>
    from .tracker import ECOTracker
  File "C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master (2)\pyCFTrackers-master\lib\eco\tracker.py", line 11, in <module>
    from .features import GrayFeature,FHogFeature, TableFeature, mround, ResNet50Feature, VGG16Feature
  File "C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master (2)\pyCFTrackers-master\lib\eco\features\__init__.py", line 1, in <module>
    from .features import GrayFeature,FHogFeature, TableFeature, fhog, mround, ResNet50Feature, VGG16Feature
  File "C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master (2)\pyCFTrackers-master\lib\eco\features\features.py", line 11, in <module>
    from . import _gradient
ImportError: cannot import name '_gradient'

**Comment by fengyang95** [comment]
看样子就是没编译成功呀  setup那里执行了？

**Comment by momo-github-1984** [comment]
您指lib/eco/features/setup.py吗？我不知道它是否执行。我是直接运行的cf_demo.py，需要怎样执行setup？我在setup中添加了一个Print语句，看起来它似乎没有被执行。

**Comment by momo-github-1984** [comment]
您好，我之前确实没有执行setup……抱歉，我不太仔细。但现在我执行setup时，也是有错误。我在想是不是是我环境的问题？
(tensorflow-m) C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master\lib\eco\features>python setup.py build_ext --inplace
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
building '_gradient' extension
creating build\temp.win-amd64-3.6
creating build\temp.win-amd64-3.6\Release
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\18382\AppData\Roaming\Python\Python36\site-packages\numpy\core\include -IC:\Users\18382\.conda\envs\tensorflow-m\include -IC:\Users\18382\.conda\envs\tensorflow-m\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\8.1\include\\shared -IC:\Program Files (x86)\Windows Kits\8.1\include\\um -IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt /EHsc /Tp_gradient.cpp /Fobuild\temp.win-amd64-3.6\Release\_gradient.obj
_gradient.cpp
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(10): fatal error C1083: �޷��򿪰����ļ�:
 ��vcruntime.h��: No such file or directory
error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\18382\AppData\Roaming\Python\Python36\site-packages\numpy\core\include -IC:\Users\18382\.conda\envs\tensorflow-m\include -IC:\Users\18382\.conda\envs\tensorflow-m\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\8.1\include\\shared -IC:\Program Files (x86)\Windows Kits\8.1\include\\um -IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt /EHsc /Tp_gradient.cpp /Fobuild\temp.win-amd64-3.6\Release\_gradient.obj" failed with exit status 2

(tensorflow-m) C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master\lib\pysot\utils>python setup.py build_ext --inplace
Compiling region.pyx because it depends on C:\Users\18382\AppData\Roaming\Python\Python36\site-packages\Cython\Includes\libc\string.pxd.
[1/1] Cythonizing region.pyx
C:\Users\18382\AppData\Roaming\Python\Python36\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master\lib\pysot\utils\region.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'region' extension
creating build\temp.win-amd64-3.6
creating build\temp.win-amd64-3.6\Release
creating build\temp.win-amd64-3.6\Release\src
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -IC:\Users\18382\.conda\envs\tensorflow-m\include -IC:\Users\18382\.conda\envs\tensorflow-m\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /Tcregion.c /Fobuild\temp.win-amd64-3.6\Release\region.obj
region.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(10): fatal error C1083: 无法打开包括文件: “vcruntime.h”: No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\cl.exe' failed with exit status 2

**Comment by fengyang95** [comment]
这个可能是权限问题 可以用管理员模式打开命令行试下？

**Comment by kkxLly** [comment]
> 您好，我之前确实没有执行setup……抱歉，我不太仔细。但现在我执行setup时，也是有错误。我在想是不是是我环境的问题？
> (tensorflow-m) C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master\lib\eco\features>python setup.py build_ext --inplace
> running build_ext
> No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
> building '_gradient' extension
> creating build\temp.win-amd64-3.6
> creating build\temp.win-amd64-3.6\Release
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\18382\AppData\Roaming\Python\Python36\site-packages\numpy\core\include -IC:\Users\18382.conda\envs\tensorflow-m\include -IC:\Users\18382.conda\envs\tensorflow-m\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\8.1\include\shared -IC:\Program Files (x86)\Windows Kits\8.1\include\um -IC:\Program Files (x86)\Windows Kits\8.1\include\winrt /EHsc /Tp_gradient.cpp /Fobuild\temp.win-amd64-3.6\Release_gradient.obj
> _gradient.cpp
> C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(10): fatal error C1083: �޷��򿪰����ļ�:
> ��vcruntime.h��: No such file or directory
> error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\18382\AppData\Roaming\Python\Python36\site-packages\numpy\core\include -IC:\Users\18382.conda\envs\tensorflow-m\include -IC:\Users\18382.conda\envs\tensorflow-m\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um -IC:\Program Files (x86)\Windows Kits\8.1\include\shared -IC:\Program Files (x86)\Windows Kits\8.1\include\um -IC:\Program Files (x86)\Windows Kits\8.1\include\winrt /EHsc /Tp_gradient.cpp /Fobuild\temp.win-amd64-3.6\Release_gradient.obj" failed with exit status 2
> 
> (tensorflow-m) C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master\lib\pysot\utils>python setup.py build_ext --inplace
> Compiling region.pyx because it depends on C:\Users\18382\AppData\Roaming\Python\Python36\site-packages\Cython\Includes\libc\string.pxd.
> [1/1] Cythonizing region.pyx
> C:\Users\18382\AppData\Roaming\Python\Python36\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\18382\Desktop\experiment\GitHub\pyCFTrackers-master\lib\pysot\utils\region.pyx
> tree = Parsing.p_module(s, pxd, full_module_name)
> running build_ext
> building 'region' extension
> creating build\temp.win-amd64-3.6
> creating build\temp.win-amd64-3.6\Release
> creating build\temp.win-amd64-3.6\Release\src
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -IC:\Users\18382.conda\envs\tensorflow-m\include -IC:\Users\18382.conda\envs\tensorflow-m\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcregion.c /Fobuild\temp.win-amd64-3.6\Release\region.obj
> region.c
> C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(10): fatal error C1083: 无法打开包括文件: “vcruntime.h”: No such file or directory
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe' failed with exit status 2

需要正确编译，建议conda一个新的环境，pip requirement.txt包，部分包可能pip安装不成功，需要自行百度解决，然后在按照README.md中编译命令操作

**Comment by momo-github-1984** [comment]
> > 您好，我之前确实没有执行setup……抱歉，我不太仔细。但现在我执行setup时，也是有错误。我在想是不是是我环境的问题？
> > （tensorflow-m）C：\ Users \ 18382 \ Desktop \ experiment \ GitHub \ pyCFTrackers-master \ lib \ eco \ features> python setup.py build_ext --inplace 
> > running build_ext在numpy.distutils中
> > 没有名为``numpy.distutils._msvccompiler''的模块; 尝试从distutils
> > 构建'_gradient'扩展名，
> > 创建build \ temp.win-amd64-3.6，
> > 创建build \ temp.win-amd64-3.6 \ Release
> > C：\ Program Files（x86）\ Microsoft Visual Studio 14.0 \ VC \ bin \ cl.exe / c / nologo / Ox / W3 / GL / DNDEBUG / MD -IC：\ Users \ 18382 \ AppData \ Roaming \ Python \ Python36 \ site-packages \ numpy \ core \ include -IC：\ Users \ 18382.conda \ envs \ tensorflow-m \ include -IC：\ Users \ 18382.conda \ envs \ tensorflow-m \ include -IC：\ Program Files （x86）\ Windows Kits \ 10 \ include \ 10.0.10240.0 \ ucrt -IC：\ Program Files（x86）\ Windows Kits \ NETFXSDK \ 4.6.1 \ include \ um -IC：\ Program Files（x86）\ Windows Kits \ 8.1 \ include \ shared -IC：\ Program Files（x86）\ Windows Kits \ 8.1 \ include \ um -IC：\ Program Files（x86）\ Windows Kits \ 8.1 \ include \ winrt / EHsc /Tp_gradient.cpp / Fobuild \ temp.win-amd64-3.6 \ Release_gradient.obj 
> > _gradient.cpp 
> > C：\ Program Files（x86）\ Windows Kits \ 10 \ include \ 10.0.10240.0 \ ucrt \ corecrt.h（10）：致命错误C1083： ޷   򿪰    ļ ：
> > vcruntime.h  ：无此类文件或目录
> > 错误：命令“ C：\ Program Files（x86）\ Microsoft Visual Studio 14.0 \ VC \ bin \ cl.exe / c / nologo / Ox / W3 / GL / DNDEBUG / MD -IC：\ Users \ 18382 \ AppData \ Roaming \ Python \ Python36 \ site-packages \ numpy \ core \ include -IC：\ Users \ 18382.conda \ envs \ tensorflow-m \ include -IC：\ Users \ 18382.conda \ envs \ tensorflow-m \ include -IC：\ Program Files（x86）\ Windows Kits \ 10 \ include \ 10.0.10240.0 \ ucrt -IC：\ Program Files（x86）\ Windows Kits \ NETFXSDK \ 4.6。 1 \ include \ um -IC：\ Program Files（x86）\ Windows Kits \ 8.1 \ include \ shared -IC：\ Program Files（x86）\ Windows Kits \ 8.1 \ include \ um -IC：\ Program Files（x86） \ Windows Kits \ 8.1 \ include \ winrt / EHsc /Tp_gradient.cpp /Fobuild\temp.win-amd64-3.6\Release_gradient.obj“失败，退出状态为2
> > （tensorflow-m）C：\ Users \ 18382 \ Desktop \ experiment \ GitHub \ pyCFTrackers-master \ lib \ pysot \ utils> python setup.py build_ext --inplace
> > 编译region.pyx，因为它取决于C：\ Users \ 18382 \ AppData \ Roaming \ Python \ Python36 \ site-packages \ Cython \ Includes \ libc \ string.pxd。
> > [1/1] Cythonizing region.pyx 
> > C：\ Users \ 18382 \ AppData \ Roaming \ Python \ Python36 \ site-packages \ Cython \ Compiler \ Main.py：369：FutureWarning：未设置Cython指令'language_level'，使用2现在（Py2）。这将在以后的版本中更改！文件：C：\ Users \ 18382 \ Desktop \ experiment \ GitHub \ pyCFTrackers-master \ lib \ pysot \ utils \ region.pyx 
> > tree = Parsing.p_module（s，pxd，full_module_name）
> > 运行build_ext
> > 构建'区域'扩展
> > 创建build \ temp.win-amd64-3.6
> > 创建build \ temp.win-amd64-3.6 \ Release
> > 创建build \ temp.win-amd64-3.6 \ Release \ src 
> > C：\ Program Files（x86）\ Microsoft Visual Studio 14.0 \ VC \ bin \ cl.exe / c / nologo / Ox / W3 / GL / DNDEBUG / MD -I。-IC：\ Users \ 18382.conda \ envs \ tensorflow-m \ include -IC：\ Users \ 18382.conda \ envs \ tensorflow-m \ include“ -IC：\ Program Files（x86）\ Windows Kits \ 10 \ include \ 10.0.10240.0 \ ucrt“” -IC：\ Program Files（x86）\ Windows Kits \ NETFXSDK \ 4.6.1 \ include \ um“” -IC：\ Program Files（x86）\ Windows Kits \ 8.1 \ include \共享“” -IC：\ Program Files（x86）\ Windows Kits \ 8.1 \ include \ um“” -IC：\ Program Files（x86）\ Windows Kits \ 8.1 \ include \ winrt“ /Tcregion.c / Fobuild \ temp .win-amd64-3.6 \ Release \ region.obj 
> > region.c
> > C：\ Program Files（x86）\ Windows Kits \ 10 \ include \ 10.0.10240.0 \ ucrt \ corecrt.h（10）：致命错误C1083：无法打开包括文件：“ vcruntime.h”：没有此类文件或目录
> > 错误：命令“ C：\ Program Files（x86）\ Microsoft Visual Studio 14.0 \ VC \ bin \ cl.exe”失败，退出状态为2
> 
> 需要正确编译，建议conda一个新的环境，pip required.txt包，部分包可能pip安装不成功，需要自行百度解决，然后在按照README.md中编译命令操作

多谢回复，这个问题我以及解决的，确实是没有成功编译！

**Comment by zhangyuran-gg** [comment]
![image](https://user-images.githubusercontent.com/101116786/162665806-497f4b43-23b1-4f9d-ac8e-c1f56a85c036.png
loading VOT2016: 100%|███████████████████████████████████████| 60/60 [00:00<00:00, 69.39it/s, wiper]
img_name: D:/VOT2016\wiper/00000001.jpg
eval ar: 100%|██████████████████████████████████████████████████████| 19/19 [00:04<00:00,  3.97it/s]
eval eao:   0%|                                                              | 0/19 [00:03<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\15979\.conda\envs\torch10.2\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "E:\cftracker_\compare_cf_tracker\pyCFTrackers-yuan\lib\pysot\evaluation\eao_benchmark.py", line 43, in eval
    eao = self._calculate_eao(tracker_name, self.tags)
  File "E:\cftracker_\compare_cf_tracker\pyCFTrackers-yuan\lib\pysot\evaluation\eao_benchmark.py", line 106, in _calculate_eao
    max_len = max([len(x) for x in all_overlaps])
ValueError: max() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:/cftracker_/compare_cf_tracker/pyCFTrackers-yuan/eval/eval_VOT2016.py", line 68, in <module>
    trackers), desc='eval eao', total=len(trackers), ncols=100):
  File "C:\Users\15979\.conda\envs\torch10.2\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\15979\.conda\envs\torch10.2\lib\multiprocessing\pool.py", line 735, in next
    raise value
ValueError: max() arg is an empty sequence

进程已结束,退出代码1
eval vot2016总是报这个错误，是为什么呢
