### ISSUE TITLE
OTB100 eval error

### ISSUE THREAD

**Issue by Xianqi-Zhang** [wwdguu/pyCFTrackers#4]
I’m sorry to disturb u with this question. I have checked the issues in pyCFTrackers and pysot-toolkit, but have no answers.

I use the eval_OTB.py to test OTB100

It raise errors：
--------------------------------------------------------------------------------------------------
File "pysot/utils/statistics.py", line 104:
def success_overlap(gt_bb, result_bb, n_frame):
    thresholds_overlap = np.arange(0, 1.05, 0.05)
    ^

This error may have been caused by the following argument(s):
- argument 1: Unsupported array dtype: object

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
--------------------------------------------------------------------------------------------------

And when i comment the # @jit(nopython=True), it raise errors：
--------------------------------------------------------------------------------------------------
"""
Traceback (most recent call last):
  File "/root/anaconda3/envs/cf/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/root/Documents/pysot-toolkit-master/pysot/evaluation/ope_benchmark.py", line 50, in eval_success
    success_ret_[video.name] = success_overlap(gt_traj, tracker_traj, n_frame)
  File "/root/Documents/pysot-toolkit-master/pysot/utils/statistics.py", line 108, in success_overlap
    iou[mask] = overlap_ratio(gt_bb[mask], result_bb[mask])
IndexError: too many indices for array
"""
--------------------------------------------------------------------------------------------------

Thank you for any reply! ! !

**Comment by fengyang95** [comment]
did you installed numba successfully?

**Comment by Xianqi-Zhang** [comment]
Hello,
I have tried many times to make sure the environment,  install/uninstall numba, conda create new environment, but it doesn't work and raise the same error.

My server is CentOS, any relationship？

Thank you for any reply.

Error log:
---------------------------------------------------------------------------------------------------------
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/eval.py", line 40, in <module>
    trackers), desc='eval success', total=len(trackers), ncols=100):
  File "/root/anaconda3/envs/cf/lib/python3.5/site-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/root/anaconda3/envs/cf/lib/python3.5/multiprocessing/pool.py", line 731, in next
    raise value
numba.errors.TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.ArgConstraint object at 0x7ff779719dd8>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/anaconda3/envs/cf/lib/python3.5/site-packages/numba/errors.py", line 577, in new_error_context
    yield
  File "/root/anaconda3/envs/cf/lib/python3.5/site-packages/numba/typeinfer.py", line 199, in __call__
    assert ty.is_precise()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/cf/lib/python3.5/site-packages/numba/typeinfer.py", line 142, in propagate
    constraint(typeinfer)
  File "/root/anaconda3/envs/cf/lib/python3.5/site-packages/numba/typeinfer.py", line 200, in __call__
    typeinfer.add_type(self.dst, ty, loc=self.loc)
  File "/root/anaconda3/envs/cf/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/anaconda3/envs/cf/lib/python3.5/site-packages/numba/errors.py", line 585, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/root/anaconda3/envs/cf/lib/python3.5/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.InternalError: 
[1] During: typing of argument at /root/Documents/pysot-toolkit-master/pysot/utils/statistics.py (104)
--%<----------------------------------------------------------------------------


File "pysot/utils/statistics.py", line 104:
def success_overlap(gt_bb, result_bb, n_frame):
    thresholds_overlap = np.arange(0.0, 1.05, 0.05)
    ^

This error may have been caused by the following argument(s):
- argument 1: Unsupported array dtype: object

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
---------------------------------------------------------------------------------------------------------

**Comment by fengyang95** [comment]
Or you can try to commit all @jit code and test again? I test this on Ubuntu16.04. Maybe you can create an issue in the original repo pysot-toolkit.

**Comment by Xianqi-Zhang** [comment]
Hello,
When i commit all @jit, it raise another question as below. It's work  when you commit like this?

Thank you for your reply. 


-------------------------------------------------------------------------------------------------------------------
"""
Traceback (most recent call last):
  File "/root/anaconda3/envs/cf/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/root/Documents/pyCFTrackers-master/lib/pysot/evaluation/ope_benchmark.py", line 50, in eval_success
    success_ret_[video.name] = success_overlap(gt_traj, tracker_traj, n_frame)
  File "/root/Documents/pyCFTrackers-master/lib/pysot/utils/statistics.py", line 108, in success_overlap
    iou[mask] = overlap_ratio(gt_bb[mask], result_bb[mask])
IndexError: too many indices for array
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "eval_OTB.py", line 39, in <module>
    trackers), desc='eval success', total=len(trackers), ncols=100):
  File "/root/anaconda3/envs/cf/lib/python3.5/site-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/root/anaconda3/envs/cf/lib/python3.5/multiprocessing/pool.py", line 731, in next
    raise value
IndexError: too many indices for array
-------------------------------------------------------------------------------------------------------------------

**Comment by fengyang95** [comment]
Yes, it works well, so i have no idea about your issue.

**Comment by Xianqi-Zhang** [comment]
Thank you for your kindly reply.

**Comment by LIANGKE23** [comment]
Do you finish your problems

**Comment by Xianqi-Zhang** [comment]
> Do you finish your problems

Not yet，I rewrote my code with MATLAB and evaluated it by track_benchamark_v1.0.
