### ISSUE TITLE
while installing the requirements, this error is popping up !! 

### ISSUE THREAD

**Issue by prerit1998jain** [wwdguu/pyCFTrackers#8]
ERROR: mxnet-cu90 1.4.1 has requirement numpy<1.15.0,>=1.8.2, but you'll have numpy 1.16.2 which is incompatible.

**Comment by fengyang95** [comment]
You can install older version of numpy to fix it.

**Comment by prerit1998jain** [comment]
Ya I did it!!

Can you tell me why is this error coming up? 
  File "cf_demo.py", line 2, in <module>
    from examples.pytracker import PyTracker
ModuleNotFoundError: No module named 'examples'

**Comment by prerit1998jain** [comment]
The above problem is solved, it seems there was some problem with the building part. Please help me with this error 
Traceback (most recent call last):
  File "cf_demo.py", line 2, in <module>
    from examples.pytracker import PyTracker
  File "/home/prerit/Desktop/Silo.Ai/pyCFTrackers/examples/pytracker.py", line 6, in <module>
    from cftracker.kcf import KCF
  File "/home/prerit/Desktop/Silo.Ai/pyCFTrackers/cftracker/kcf.py", line 7, in <module>
    from .feature import extract_hog_feature,extract_cn_feature
  File "/home/prerit/Desktop/Silo.Ai/pyCFTrackers/cftracker/feature.py", line 3, in <module>
    from lib.eco.features.features import fhog,TableFeature
  File "/home/prerit/Desktop/Silo.Ai/pyCFTrackers/lib/eco/__init__.py", line 1, in <module>
    from .tracker import ECOTracker
  File "/home/prerit/Desktop/Silo.Ai/pyCFTrackers/lib/eco/tracker.py", line 11, in <module>
    from .features import GrayFeature,FHogFeature, TableFeature, mround, ResNet50Feature, VGG16Feature
  File "/home/prerit/Desktop/Silo.Ai/pyCFTrackers/lib/eco/features/__init__.py", line 1, in <module>
    from .features import GrayFeature,FHogFeature, TableFeature, fhog, mround, ResNet50Feature, VGG16Feature
  File "/home/prerit/Desktop/Silo.Ai/pyCFTrackers/lib/eco/features/features.py", line 1, in <module>
    import mxnet as mx
  File "/home/prerit/anaconda3/envs/computervision/lib/python3.7/site-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/prerit/anaconda3/envs/computervision/lib/python3.7/site-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/home/prerit/anaconda3/envs/computervision/lib/python3.7/site-packages/mxnet/base.py", line 213, in <module>
    _LIB = _load_lib()
  File "/home/prerit/anaconda3/envs/computervision/lib/python3.7/site-packages/mxnet/base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/home/prerit/anaconda3/envs/computervision/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.1: cannot open shared object file: No such file or directory

**Comment by fengyang95** [comment]
It seems that something wrong with your cuda environment.

**Comment by prerit1998jain** [comment]
Can you suggest something? Which Cuda version did you use?

**Comment by fengyang95** [comment]
I used cuda 9.0 The mxnet version should be matched with cuda version.

**Comment by prerit1998jain** [comment]
Will it work if I use cuda 10.0 and the mxnet version which match it? Or there will be compatibility issues with other packages?

**Comment by fengyang95** [comment]
I just tested on cuda 9.0.

**Comment by prerit1998jain** [comment]
Thanks for the answers. I guess it is working now. I build an environment with mxnet90 and cuda9.0. And it is running in it. Thanks for your help!!
